# cuota-service-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuota-deployment
  labels:
    app: cuota-deployment
spec:
  selector:
    matchLabels:
      app: cuota-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: cuota-deployment
    spec:
      containers:
        - name: cuota-service
          image: nachowo/cuotas-service:latest  
          ports:
            - containerPort: 8082  # Puedes cambiar el puerto si es necesario
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DS_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DS_HOST 
            - name: POSTGRES_DB_CUOTAS  # Cambiado el nombre para reflejar la base de datos de cuotas
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB_CUOTAS  # Cambiado el nombre para reflejar la base de datos de cuotas
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
# cuota-service-service.yml
apiVersion: v1
kind: Service
metadata:
  name: cuota-service
  labels:
    app: cuota-service
spec:
  selector:
    app: cuota-deployment
  ports:
    - protocol: TCP
      port: 8092  # Puedes cambiar el puerto si es necesario
      targetPort: 8082  # Debe coincidir con el puerto del contenedor
  type: LoadBalancer
