apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuotas-deployment
  labels:
    app: cuotas-deployment
spec:
  selector:
    matchLabels:
      app: cuotas-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: cuotas-deployment
    spec:
      containers:
        - name: cuotas-service
          image: nachowo/cuotas-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DS_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DS_HOST 
            - name: POSTGRES_DB_CUOTAS
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB_CUOTAS
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cuotas-service
  labels:
    app: cuotas-service
spec:
  selector:
    app: cuotas-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: LoadBalancer