apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-deployment
spec:
  selector:
    matchLabels:
      app: front-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: front-deployment
    spec:
      containers:
        - name: front-service
          image: nachowo/front-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  selector:
    app: front-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer